# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e88fc06c15f55ec6de85ba2e73464c017ad1ae17311e0213fc3f1d97cd8b7d7b3156bae8e0ba2721691fcc51f4fde647e12983a28b3b6dfef36b45a1ff9fd23c

test:
  secret_key_base: 8651cd132ea06b3a2d6076cb7b6802a0ba83d3adda9f8ee8480cda9d211b63392502062a9cf82a6c2360849b0453b1056a146c10579401eb21851abe515a682d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
